
services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=mebel_db
      - POSTGRES_USER=mebel_user
      - POSTGRES_PASSWORD=mebel_secure_pass
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  web:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DB_HOST=db
      - DB_NAME=mebel_db
      - DB_USER=mebel_user
      - DB_PASSWORD=mebel_secure_pass
      - DJANGO_DEBUG=True
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1
      - DJANGO_CSRF_TRUSTED_ORIGINS=https://cognoscitive-kristeen-hypoxic.ngrok-free.dev

volumes:
  postgres_data:
