# Generated by Django 6.0.1 on 2026-03-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Картинка'),
        ),
        migrations.AddField(
            model_name='category',
            name='show_on_main',
            field=models.BooleanField(default=True, verbose_name='Показывать категорию на главной странице'),
        ),
    ]
