# Generated by Django 6.0.1 on 2026-04-20 12:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_category_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_slug',
            field=models.SlugField(blank=True, default='prod_slug', max_length=255, unique=True, validators=[django.core.validators.RegexValidator(message='Слаг может содержать только латиницу, цифры и дефис (никаких пробелов и подчеркиваний!)', regex='^[a-z0-9-]+$')]),
        ),
    ]
