# Generated by Django 6.0.1 on 2026-05-11 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_product_og_description_product_og_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='og_description',
            field=models.TextField(blank=True, max_length=220, null=True, verbose_name='og:description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='seo_description',
            field=models.TextField(blank=True, max_length=220, null=True, verbose_name='meta description'),
        ),
    ]
