# Generated by Django 6.0.1 on 2026-05-12 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_seo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seo',
            options={'verbose_name': 'SEO настройки страниц', 'verbose_name_plural': 'SEO настройки страниц'},
        ),
        migrations.AddField(
            model_name='seo',
            name='catalog_h1',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='meta description /catalog/'),
        ),
        migrations.AddField(
            model_name='seo',
            name='contacts_h1',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='meta description /contacts/'),
        ),
        migrations.AddField(
            model_name='seo',
            name='main_h1',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='meta description /main/'),
        ),
        migrations.AddField(
            model_name='seo',
            name='policy_h1',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='meta description /policy/'),
        ),
        migrations.AddField(
            model_name='seo',
            name='projects_h1',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='meta description /projects/'),
        ),
    ]
