# Generated by Django 6.0.1 on 2026-05-14 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_setting_map_alter_category_name_alter_seo_catalog_h1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='map',
            field=models.TextField(blank=True, unique=True, verbose_name='Скрипт карты'),
        ),
    ]
