# Generated by Django 6.0.1 on 2026-05-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_alter_faqitem_options_remove_faqitem_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqitem',
            name='page',
            field=models.CharField(blank=True, choices=[('main', 'Главная страница'), ('catalog', 'Каталог'), ('contacts', 'Контакты'), ('cooperation', 'Сотрудничество'), ('restoration', 'Реставрация'), ('projects', 'Проекты'), ('restoration', 'Реставрация'), ('cooperation', 'Сотрудничество'), ('policy', 'Политика конф.')], max_length=20, null=True, verbose_name='Для базовой страницы'),
        ),
    ]
