events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # Настройки безопасности: скрываем версию Nginx и настраиваем лимиты
    server_tokens off;
    client_max_body_size 100M; # Чтобы можно было загружать тяжелые фотки мебели

    # Логи
    access_log /var/log/nginx/access.log;
    error_log  /var/log/nginx/error.log;

    # Gzip сжатие (чтобы сайт мебели грузился быстрее)
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml;

    server {
        listen 80;
        listen [::]:80;
        server_name uralmeb.ru www.uralmeb.ru 82.202.128.193;
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;
        listen [::]:443 ssl;
        server_name uralmeb.ru www.uralmeb.ru;

        # Пути к файлам сертификатов, которые мы прокинули через Докер
        ssl_certificate /etc/letsencrypt/live/uralmeb.ru/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/uralmeb.ru/privkey.pem;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;

        # Раздача статики (путь внутри контейнера Nginx)
        location /static/ {
            alias /app/staticfiles_collected/;
            expires 30d;
            add_header Cache-Control "public, no-transform";
        }

        # Раздача картинок мебели (путь внутри контейнера Nginx)
        location /media/ {
            alias /app/media/;
            expires 30d;
            add_header Cache-Control "public, no-transform";
        }

        # Все остальные запросы перекидываем в контейнер Джанги на Gunicorn
        location / {
            proxy_pass http://web:8000;
            
            # Передаем реальные заголовки, чтобы Django не сходила с ума
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            
            # Лимиты ожидания, чтобы долгие запросы не отваливались
            proxy_connect_timeout 90;
            proxy_send_timeout 90;
            proxy_read_timeout 90;
        }
    }
}
