# Generated by Django 6.0.1 on 2026-03-04 17:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category_slug', models.SlugField(blank=True, max_length=255, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Слаг может содержать только латиницу, цифры и дефис (никаких пробелов и подчеркиваний!)', regex='^[a-z0-9-]+$')])),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='', max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(default='', max_length=254, verbose_name='Email адрес')),
                ('working_hours', models.CharField(default='', max_length=255, verbose_name='Режим работы')),
                ('address', models.CharField(default='', max_length=255, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Настройка сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_slug', models.SlugField(blank=True, max_length=255, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Слаг может содержать только латиницу, цифры и дефис (никаких пробелов и подчеркиваний!)', regex='^[a-z0-9-]+$')])),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('subtitle', models.CharField(default='Велюр, массив кедра, индивидуальный размер.', max_length=150, verbose_name='Подзаголовок')),
                ('is_from', models.BooleanField(default=False, verbose_name='от')),
                ('is_green', models.BooleanField(default=False, verbose_name='зеленый ценник')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Картинка')),
                ('is_new', models.BooleanField(default=False, verbose_name='Новинка')),
                ('material', models.CharField(default='Массив кедра, Велюр', max_length=255, verbose_name='Материал')),
                ('production_time', models.CharField(default='от 22 дней', max_length=100, verbose_name='Срок изготовления')),
                ('dimensions', models.CharField(default='19000 x 1400 x 950 мм', max_length=100, verbose_name='Габариты')),
                ('description', models.TextField(default='Изысканный диван ручной работы. Мы используем только экологичные материалы. Возможен выбор цвета ткани под ваш интерьер.', verbose_name='Описание')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/extra/', verbose_name='Доп. фото')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app1.product')),
            ],
        ),
    ]
