# Generated by Django 6.0.1 on 2026-03-06 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_category_category_image_category_show_on_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='show_on_catalog',
            field=models.BooleanField(default=True, verbose_name='Показывать категорию в каталоге'),
        ),
    ]
