# Generated by Django 6.0.1 on 2026-04-20 11:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_category_show_on_catalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_slug',
            field=models.SlugField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Слаг может содержать только латиницу, цифры и дефис (никаких пробелов и подчеркиваний!)', regex='^[a-z0-9-]+$')]),
        ),
    ]
