# Generated by Django 6.0.1 on 2026-01-31 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='description',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='setting',
            name='dimensions',
            field=models.CharField(default='', max_length=100, verbose_name='Габариты'),
        ),
        migrations.AddField(
            model_name='setting',
            name='material',
            field=models.CharField(default='', max_length=255, verbose_name='Материал'),
        ),
        migrations.AddField(
            model_name='setting',
            name='production_time',
            field=models.CharField(default='', max_length=100, verbose_name='Срок изготовления'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='address',
            field=models.CharField(default='', max_length=255, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='Email адрес'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='phone',
            field=models.CharField(default='', max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='working_hours',
            field=models.CharField(default='', max_length=255, verbose_name='Режим работы'),
        ),
    ]
