# Generated by Django 6.0.1 on 2026-01-31 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_setting_description_setting_dimensions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='description',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='dimensions',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='material',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='production_time',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='dimensions',
            field=models.CharField(default='', max_length=100, verbose_name='Габариты'),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(default='', max_length=255, verbose_name='Материал'),
        ),
        migrations.AddField(
            model_name='product',
            name='production_time',
            field=models.CharField(default='', max_length=100, verbose_name='Срок изготовления'),
        ),
    ]
