# Generated by Django 6.0.1 on 2026-01-31 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_remove_setting_description_remove_setting_dimensions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subtitle',
            field=models.CharField(default='', max_length=150, verbose_name='Подзаголовок'),
        ),
    ]
