# Generated by Django 6.0.1 on 2026-02-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_alter_product_description_alter_product_dimensions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='dimensions',
            field=models.CharField(max_length=100, null=True, verbose_name='Габариты'),
        ),
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.CharField(max_length=255, null=True, verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='product',
            name='production_time',
            field=models.CharField(max_length=100, null=True, verbose_name='Срок изготовления'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subtitle',
            field=models.CharField(max_length=150, null=True, verbose_name='Подзаголовок'),
        ),
    ]
