# Generated by Django 6.0.1 on 2026-04-20 13:28

import app1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_alter_product_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to=app1.models.get_product_upload_path, verbose_name='Картинка'),
        ),
    ]
