# Generated by Django 6.0.1 on 2026-04-20 16:22

import app1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_alter_product_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='main_image_webp',
            field=models.ImageField(blank=True, null=True, upload_to=app1.models.GenerateUploadPath(where='products', subfolder='webp/'), verbose_name='Webp картинка'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_webp',
            field=models.ImageField(blank=True, null=True, upload_to=app1.models.GenerateUploadPath(where='products', subfolder='webp/'), verbose_name='Доп. фото Webp'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=app1.models.GenerateUploadPath(where='products'), verbose_name='Доп. фото'),
        ),
    ]
