# Generated by Django 6.0.1 on 2026-02-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_alter_product_description_alter_product_dimensions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='Изысканный диван ручной работы. Мы используем только экологичные материалы. Возможен выбор цвета ткани под ваш интерьер.', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='dimensions',
            field=models.CharField(default='19000 x 1400 x 950 мм', max_length=100, verbose_name='Габариты'),
        ),
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.CharField(default='Массив кедра, Велюр', max_length=255, verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='product',
            name='production_time',
            field=models.CharField(default='от 22 дней', max_length=100, verbose_name='Срок изготовления'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subtitle',
            field=models.CharField(default='Велюр, массив кедра, индивидуальный размер.', max_length=150, verbose_name='Подзаголовок'),
        ),
    ]
