# Generated by Django 6.0.1 on 2026-04-24 06:46

import app1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_product_main_image_webp_productimage_image_webp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_image_webp',
            field=models.ImageField(blank=True, null=True, upload_to=app1.models.GenerateUploadPath(subfolder='webp/', where='categories'), verbose_name='Webp картинка'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.ImageField(blank=True, null=True, upload_to=app1.models.GenerateUploadPath(where='categories'), verbose_name='Картинка'),
        ),
    ]
