# Generated by Django 6.0.1 on 2026-02-02 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_from',
            field=models.BooleanField(default=False, verbose_name='от'),
        ),
    ]
