# Generated by Django 6.0.1 on 2026-05-11 05:59

import app1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_category_category_image_webp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='og_description',
            field=models.CharField(blank=True, max_length=220, null=True, verbose_name='og:description'),
        ),
        migrations.AddField(
            model_name='product',
            name='og_image',
            field=models.ImageField(blank=True, null=True, upload_to=app1.models.GenerateUploadPath(subfolder='og_image/', where='products'), verbose_name='Картинка'),
        ),
        migrations.AddField(
            model_name='product',
            name='og_title',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='og:title'),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_description',
            field=models.CharField(blank=True, max_length=220, null=True, verbose_name='meta description'),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_title',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='title'),
        ),
    ]
