# Generated by Django 6.0.1 on 2026-02-02 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_product_is_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_green',
            field=models.BooleanField(default=False, verbose_name='зеленый ценник'),
        ),
    ]
