# Generated by Django 6.0.1 on 2026-05-11 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_alter_product_og_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(blank=True, max_length=150, null=True, verbose_name='title /main/')),
                ('main_description', models.TextField(blank=True, max_length=220, null=True, verbose_name='meta description /main/')),
                ('catalog_title', models.CharField(blank=True, max_length=150, null=True, verbose_name='title /catalog/')),
                ('catalog_description', models.TextField(blank=True, max_length=220, null=True, verbose_name='meta description /catalog/')),
                ('contacts_title', models.CharField(blank=True, max_length=150, null=True, verbose_name='title /contacts/')),
                ('contacts_description', models.TextField(blank=True, max_length=220, null=True, verbose_name='meta description /contacts/')),
                ('projects_title', models.CharField(blank=True, max_length=150, null=True, verbose_name='title /projects/')),
                ('projects_description', models.TextField(blank=True, max_length=220, null=True, verbose_name='meta description /projects/')),
                ('policy_title', models.CharField(blank=True, max_length=150, null=True, verbose_name='title /policy/')),
                ('policy_description', models.TextField(blank=True, max_length=220, null=True, verbose_name='meta description /policy/')),
            ],
        ),
    ]
