# Generated by Django 6.0.1 on 2026-05-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_alter_seo_options_seo_catalog_h1_seo_contacts_h1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='map',
            field=models.CharField(blank=True, max_length=200, unique=True, verbose_name='Скрипт карты'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='seo',
            name='catalog_h1',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='h1 /catalog/'),
        ),
        migrations.AlterField(
            model_name='seo',
            name='contacts_h1',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='h1 /contacts/'),
        ),
        migrations.AlterField(
            model_name='seo',
            name='main_h1',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='h1 /main/'),
        ),
        migrations.AlterField(
            model_name='seo',
            name='policy_h1',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='h1 /policy/'),
        ),
        migrations.AlterField(
            model_name='seo',
            name='projects_h1',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='h1 /projects/'),
        ),
    ]
