# Generated by Django 6.0.1 on 2026-05-14 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_alter_setting_map'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='map',
            new_name='map_script',
        ),
    ]
