# Generated by Django 6.0.1 on 2026-05-19 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_alter_setting_map_script_faqitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqitem',
            options={'ordering': ['order'], 'verbose_name': 'Вопрос-ответ', 'verbose_name_plural': 'FAQ (Вопросы и ответы)'},
        ),
        migrations.RemoveField(
            model_name='faqitem',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='faqitem',
            name='object_id',
        ),
        migrations.AddField(
            model_name='faqitem',
            name='page',
            field=models.CharField(blank=True, choices=[('main', 'Главная страница'), ('catalog', 'Каталог'), ('contacts', 'Контакты'), ('cooperation', 'Сотрудничество')], max_length=20, null=True, verbose_name='Для базовой страницы'),
        ),
        migrations.AddField(
            model_name='faqitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.product', verbose_name='Или для конкретного товара'),
        ),
        migrations.AddField(
            model_name='faqitem',
            name='url_path',
            field=models.CharField(blank=True, help_text='Например: /catalog/stul-vintazhny/', max_length=255, null=True, verbose_name='Или для любого точного URL-пути'),
        ),
    ]
