name: Django Auto Deploy

on:
  push:
    branches:
      - main  # Запуск только при пуше в главную ветку

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
            # Копируем папку nginx с конфигом из Гитхаба прямо на твой сервер
      - name: Copy Nginx config to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: "nginx/nginx.conf"
          target: "/home/vito/mebel-project/"
      # 1. Забираем код из твоего GitHub репозитория
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Логинимся в Docker Hub через твои секреты
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. Собираем свежий образ Django и заливаем его на Docker Hub
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: vitaliitutovic2018/mebel-django:latest

      # 4. Собираем и пушим кастомный Nginx на Docker Hub
      - name: Build and push Nginx image
        uses: docker/build-push-action@v5
        with:
          context: ./nginx
          file: ./nginx/Dockerfile
          push: true
          tags: vitaliitutovic2018/mebel-nginx:latest

      # 5. САМЫЙ ВАЖНЫЙ ШАГ: Гитхаб сам копирует файл docker-compose на сервер!
      - name: Copy docker-compose to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: "docker-compose.prod.yml"
          target: "/home/vito/mebel-project/"
        
      # 6. Заходим на твой сервер по SSH и обновляем проект
      - name: SSH Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            # Переходим в папку проекта (ЕСЛИ ПУТЬ ДРУГОЙ — ЗАМЕНИ ТУТ НА СВОЙ!)
            cd /home/vito/mebel-project
            
            # Скачиваем новый образ web с Docker Hub
            docker compose -f docker-compose.prod.yml pull
            
            # Перезапускаем контейнеры в фоновом режиме
            docker compose -f docker-compose.prod.yml up -d
            
            # Накатываем миграции и собираем статику внутри контейнера web
            docker compose -f docker-compose.prod.yml exec -T web python manage.py migrate --noinput
            docker compose -f docker-compose.prod.yml exec -T web python manage.py collectstatic --noinput --clear
            
            # Удаляем старый хлам, чтобы не забивать диск сервера
            docker image prune -f
